---

- import_playbook: "./post-installation-verification"

- hosts: localhost
  gather_facts: no
  tasks:
    - name: Verify cluster ready state.
      shell: "oc -n middleware-monitoring exec -i -t prometheus-application-monitoring-0 -c prometheus -- /bin/sh -c \"curl http://localhost:9090/api/v1/query?query=ALERTS\" | jq .data.result"
        