---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Fetch cluster ready state.
      shell: oc -n middleware-monitoring exec -i prometheus-application-monitoring-0 -c prometheus -- /bin/sh -c "curl http://localhost:9090/api/v1/query?query=ALERTS" | jq .data.result
      register: alerts_response
    
    - set_fact:
        alerts: "{{alerts_response.stdout|from_json}}"

    - name: test loop
      debug:
        msg: "{{item.key}}"
      with_dict: "{{ alerts['metric'] }}"
      