---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Get cluster ready state.
      shell: oc -n middleware-monitoring exec -i prometheus-application-monitoring-0 -c prometheus -- /bin/sh -c "curl http://localhost:9090/api/v1/query?query=ALERTS" | jq .data.result
      register: alerts_response

    - name: Verify cluster ready state.
      fail:
        msg: "Cluster not ready, alerts found"
      when: '"ALERTS" not in alerts_response.stdout'

    - debug:
        msg: Alerts {{ alerts_response.stdout }}